version: '3.8'

services:
  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://seiketsu_user:seiketsu_pass@postgres:5432/seiketsu_ai
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - ELEVEN_LABS_API_KEY=${ELEVEN_LABS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - seiketsu-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=seiketsu_ai
      - POSTGRES_USER=seiketsu_user
      - POSTGRES_PASSWORD=seiketsu_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - seiketsu-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - seiketsu-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Celery Worker (for background tasks)
  worker:
    build: .
    command: celery -A app.core.celery worker --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://seiketsu_user:seiketsu_pass@postgres:5432/seiketsu_ai
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - ELEVEN_LABS_API_KEY=${ELEVEN_LABS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - seiketsu-network
    restart: unless-stopped

  # Celery Beat (for scheduled tasks)
  beat:
    build: .
    command: celery -A app.core.celery beat --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://seiketsu_user:seiketsu_pass@postgres:5432/seiketsu_ai
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - seiketsu-network
    restart: unless-stopped

  # Nginx (Production Load Balancer)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - seiketsu-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  seiketsu-network:
    driver: bridge